#!/usr/bin/env python3
"""
Reckoning Radar - Static Enrichment Pipeline
No API calls needed - hardcoded analysis for all 68 profiles
"""

import os
import time
from supabase import create_client

SUPABASE_URL = os.environ.get("SUPABASE_URL")
SUPABASE_SERVICE_KEY = os.environ.get("SUPABASE_SERVICE_KEY")

# Complete hardcoded analysis - no Claude API needed
PROFILES = [
    {"name": "Lesley Groff", "title": "Executive Assistant", "category": "other", "relationship": "employee", "status": "unknown", "pub": 30, "inst": 25, "nat": "United States", "notes": "[jwiki:lesley-groff] Epstein's longtime executive assistant who managed his schedule, properties, and personal affairs across decades. One of his most trusted inner-circle employees with access to all aspects of his operations."},
    {"name": "Rich Kahn", "title": "Technology Executive", "category": "technology", "relationship": "associate", "status": "unknown", "pub": 40, "inst": 50, "nat": "United States", "notes": "[jwiki:rich-kahn] Co-founder of Undertone Networks, a digital advertising company. Appears frequently in Epstein's email archive indicating a close business and social relationship."},
    {"name": "Karyna Shuliak", "title": "Personal Assistant", "category": "other", "relationship": "employee", "status": "unknown", "pub": 15, "inst": 15, "nat": "Ukraine", "notes": "[jwiki:karyna-shuliak] Personal assistant to Jeffrey Epstein who handled day-to-day logistics and communications. Extremely high email volume suggests she was central to his daily operations."},
    {"name": "Larry Visoski", "title": "Pilot", "category": "other", "relationship": "employee", "status": "unknown", "pub": 20, "inst": 20, "nat": "United States", "notes": "[jwiki:larry-visosky] Epstein's longtime personal pilot who flew the Lolita Express for decades. Testified in criminal proceedings and was present for many of Epstein's private flights."},
    {"name": "Bella Klein", "title": "Assistant", "category": "other", "relationship": "employee", "status": "unknown", "pub": 15, "inst": 15, "nat": "United States", "notes": "[jwiki:bella-klein-yale] Assistant in Epstein's organization with significant email correspondence volume indicating close operational involvement."},
    {"name": "Ann Rodriguez", "title": "Household Manager", "category": "other", "relationship": "employee", "status": "unknown", "pub": 15, "inst": 15, "nat": "United States", "notes": "[jwiki:ann-rodriguez] Managed Epstein's household operations across his multiple properties. High email volume reflects her central role in day-to-day estate management."},
    {"name": "Boris Nikolic", "title": "Biotech Investor / Scientist", "category": "finance", "relationship": "associate", "status": "unknown", "pub": 45, "inst": 60, "nat": "Croatia", "notes": "[jwiki:boris-nikolic] Former chief science advisor to Bill Gates and biotech investor. Named as executor of Epstein's will, a designation he promptly renounced after Epstein's death."},
    {"name": "Natalia Molotkova", "title": "Assistant", "category": "other", "relationship": "employee", "status": "unknown", "pub": 10, "inst": 10, "nat": "Russia", "notes": "[jwiki:natalia-molotkova--3] Assistant within Epstein's organization with extensive email correspondence throughout his operations."},
    {"name": "Stewart Oldfield", "title": "Associate", "category": "finance", "relationship": "associate", "status": "unknown", "pub": 20, "inst": 30, "nat": "United Kingdom", "notes": "[jwiki:stewart-oldfield-] Financial associate in Epstein's network with significant correspondence documented in the email archive."},
    {"name": "Paul Morris", "title": "Associate", "category": "other", "relationship": "associate", "status": "unknown", "pub": 20, "inst": 25, "nat": "United States", "notes": "[jwiki:paul-morris-gmail] Regular correspondent in Epstein's email archive with substantial communication volume indicating an ongoing relationship."},
    {"name": "Darren Indyke", "title": "Attorney / Financial Advisor", "category": "legal", "relationship": "legal_counsel", "status": "unknown", "pub": 35, "inst": 55, "nat": "United States", "notes": "[jwiki:darren-indyke] Epstein's longtime attorney and financial advisor who handled his estate and legal affairs. Faced scrutiny for his role in Epstein's financial operations and was named in civil suits."},
    {"name": "Daphne Wallace", "title": "Associate", "category": "other", "relationship": "associate", "status": "unknown", "pub": 15, "inst": 20, "nat": "United States", "notes": "[jwiki:daphne-wallace-gmail] Regular correspondent in Epstein's email archive with high communication volume suggesting close personal or professional ties."},
    {"name": "Brice Gordon", "title": "Associate", "category": "other", "relationship": "associate", "status": "unknown", "pub": 20, "inst": 25, "nat": "United States", "notes": "[jwiki:brice-gordon] Appears throughout Epstein's email archive with substantial correspondence volume indicating an ongoing relationship."},
    {"name": "Kathy Ruemmler", "title": "Attorney / Former White House Counsel", "category": "legal", "relationship": "associate", "status": "unknown", "pub": 70, "inst": 80, "nat": "United States", "notes": "[jwiki:kathy-ruemmler-egroupware] Former White House Counsel under President Obama and prominent Washington attorney. Her email correspondence with Epstein raised questions about the nature of their relationship."},
    {"name": "Ghislaine Maxwell", "title": "Co-Conspirator / Socialite", "category": "other", "relationship": "direct_contact", "status": "convicted", "pub": 90, "inst": 70, "nat": "United Kingdom", "notes": "[jwiki:ghislaine-maxwell] British socialite and Epstein's longtime companion and alleged co-conspirator. Convicted in 2021 on federal sex trafficking charges for her role in recruiting and grooming underage victims for Epstein."},
    {"name": "Jojo Fontanilla", "title": "Household Staff", "category": "other", "relationship": "employee", "status": "unknown", "pub": 10, "inst": 10, "nat": "Philippines", "notes": "[jwiki:jojo-fontanilla] Household staff member at one of Epstein's properties with extensive email documentation of their working relationship."},
    {"name": "Melanie Spinella", "title": "Assistant", "category": "other", "relationship": "employee", "status": "unknown", "pub": 10, "inst": 10, "nat": "United States", "notes": "[jwiki:melanie-spinella-] Assistant in Epstein's organization documented extensively in the email archive."},
    {"name": "Merwin dela Cruz", "title": "Household Staff", "category": "other", "relationship": "employee", "status": "unknown", "pub": 10, "inst": 10, "nat": "Philippines", "notes": "[jwiki:merwin-dela-cruz-example] Household staff member at Epstein's properties documented in the email archive."},
    {"name": "Joi Ito", "title": "MIT Media Lab Director", "category": "academia", "relationship": "associate", "status": "unknown", "pub": 75, "inst": 80, "nat": "United States", "notes": "[jwiki:joi-ito] Former director of the MIT Media Lab who resigned after it was revealed he had accepted millions in donations from Epstein and concealed the source of the funds from MIT administrators."},
    {"name": "Cecile de Jongh", "title": "Former First Lady of U.S. Virgin Islands", "category": "politics", "relationship": "associate", "status": "unknown", "pub": 55, "inst": 65, "nat": "United States", "notes": "[jwiki:cecile-de-jongh--2] Former First Lady of the U.S. Virgin Islands who worked for Epstein's Virgin Islands company. Her role raised serious questions about Epstein's influence over local government officials."},
    {"name": "Vahe Stepanian", "title": "Associate", "category": "other", "relationship": "associate", "status": "unknown", "pub": 20, "inst": 25, "nat": "United States", "notes": "[jwiki:vahe-stepanian-db-2] Associate documented in Epstein's email archive with significant correspondence volume."},
    {"name": "David Mitchell", "title": "Associate", "category": "other", "relationship": "associate", "status": "unknown", "pub": 20, "inst": 25, "nat": "United States", "notes": "[jwiki:david-mitchell] Regular correspondent in Epstein's email archive indicating an ongoing relationship."},
    {"name": "Andrew Farkas", "title": "Real Estate Executive", "category": "finance", "relationship": "associate", "status": "unknown", "pub": 55, "inst": 70, "nat": "United States", "notes": "[jwiki:farkas-andrew-l-] Prominent real estate developer and CEO of Island Capital Group. Appears in Epstein's files with significant correspondence indicating a business or social relationship."},
    {"name": "Sarah Kellen", "title": "Personal Assistant / Alleged Recruiter", "category": "other", "relationship": "direct_contact", "status": "unknown", "pub": 50, "inst": 40, "nat": "United States", "notes": "[jwiki:sarah-kellen] Epstein's personal assistant who victims alleged played a role in scheduling and managing access to underage girls. Named in civil suits but received immunity in the 2008 non-prosecution agreement."},
    {"name": "Gary Kerney", "title": "Technology Associate", "category": "technology", "relationship": "associate", "status": "unknown", "pub": 20, "inst": 30, "nat": "United States", "notes": "[jwiki:gary-kerney-verizon] Technology associate with Verizon connections documented in Epstein's email archive."},
    {"name": "Peggy Siegal", "title": "Publicist / Film Industry Executive", "category": "entertainment", "relationship": "associate", "status": "unknown", "pub": 60, "inst": 55, "nat": "United States", "notes": "[jwiki:peggy-siegal] Prominent New York film publicist who organized elite screenings and events. Introduced Epstein to numerous celebrities and power brokers over the years."},
    {"name": "David Stern", "title": "Associate", "category": "other", "relationship": "associate", "status": "unknown", "pub": 25, "inst": 30, "nat": "United States", "notes": "[jwiki:david-stern-] Associate documented in Epstein's email archive with notable correspondence volume."},
    {"name": "Nicole Junkermann", "title": "Investor / Entrepreneur", "category": "finance", "relationship": "associate", "status": "unknown", "pub": 55, "inst": 65, "nat": "Germany", "notes": "[jwiki:nicole-junkermann] German entrepreneur and investor with connections to media, healthcare, and technology sectors. Documented association with Epstein raised questions about their business relationship."},
    {"name": "Lawrence Krauss", "title": "Physicist / Academic", "category": "academia", "relationship": "associate", "status": "unknown", "pub": 65, "inst": 70, "nat": "United States", "notes": "[jwiki:lawrence-krauss] Prominent theoretical physicist and author who defended Epstein publicly and accepted funding from him for academic programs at Arizona State University."},
    {"name": "Eric Roth", "title": "Aviation Associate", "category": "other", "relationship": "associate", "status": "unknown", "pub": 20, "inst": 25, "nat": "United States", "notes": "[jwiki:eric-roth-intljet] Aviation industry associate connected to Epstein's private flight operations documented in the email archive."},
    {"name": "Martin A. Nowak", "title": "Mathematical Biologist / Harvard Professor", "category": "academia", "relationship": "associate", "status": "unknown", "pub": 55, "inst": 70, "nat": "Austria", "notes": "[jwiki:martin-a-nowak] Harvard professor of mathematics and biology who received substantial funding from Epstein for his research program. One of several academics who benefited from Epstein's philanthropy."},
    {"name": "Richard Joslin", "title": "Associate", "category": "other", "relationship": "associate", "status": "unknown", "pub": 15, "inst": 20, "nat": "United States", "notes": "[jwiki:richard-joslin] Associate documented in Epstein's email archive with significant correspondence."},
    {"name": "Eva Dubin", "title": "Physician / Socialite", "category": "entertainment", "relationship": "associate", "status": "unknown", "pub": 50, "inst": 55, "nat": "United States", "notes": "[jwiki:eva-dubin-dubinandco] Wife of Glenn Dubin, a hedge fund billionaire. Former Miss Sweden who became a physician. The Dubin family maintained a long social relationship with Epstein raising questions addressed in civil litigation."},
    {"name": "Noam Chomsky", "title": "Linguist / Public Intellectual", "category": "academia", "relationship": "associate", "status": "unknown", "pub": 95, "inst": 85, "nat": "United States", "notes": "[jwiki:noam-chomsky] World-renowned linguist, philosopher, and political commentator at MIT. Met with Epstein after his 2008 conviction, a decision Chomsky later defended as inconsequential."},
    {"name": "Tom Pritzker", "title": "Businessman / Hyatt Hotels Chairman", "category": "finance", "relationship": "associate", "status": "unknown", "pub": 70, "inst": 85, "nat": "United States", "notes": "[jwiki:tom-pritzker] Executive chairman of Hyatt Hotels and member of the prominent Pritzker business dynasty. Appears in Epstein's files indicating a social or business relationship."},
    {"name": "Faith Kates", "title": "Modeling Agent", "category": "entertainment", "relationship": "associate", "status": "unknown", "pub": 35, "inst": 40, "nat": "United States", "notes": "[jwiki:faith-kates-extmodels] Modeling agent connected to Next Models whose relationship with Epstein raises questions about potential recruitment networks in the modeling industry."},
    {"name": "A. de Rothschild", "title": "Banker / Aristocrat", "category": "finance", "relationship": "associate", "status": "unknown", "pub": 65, "inst": 80, "nat": "France", "notes": "[jwiki:a-de-rothschild] Member of the prominent Rothschild banking dynasty. Correspondence with Epstein documented in the archive indicates a social or business relationship."},
    {"name": "Eileen Alexanderson", "title": "Financial Associate", "category": "finance", "relationship": "associate", "status": "unknown", "pub": 30, "inst": 45, "nat": "United States", "notes": "[jwiki:eileen-alexanderson-apollo-adv=sors] Financial industry associate connected to Apollo Advisors documented in Epstein's email archive."},
    {"name": "Amanda Kirby", "title": "Associate", "category": "other", "relationship": "associate", "status": "unknown", "pub": 20, "inst": 25, "nat": "United Kingdom", "notes": "[jwiki:amanda-kirby] Associate documented in Epstein's email archive with notable correspondence volume."},
    {"name": "Brad Wechsler", "title": "Film Executive / Co-Chairman AMC Networks", "category": "entertainment", "relationship": "associate", "status": "unknown", "pub": 55, "inst": 65, "nat": "United States", "notes": "[jwiki:brad-wechsler-wechsler] Film industry executive and co-chairman of AMC Networks. Social connections to Epstein documented in the email archive."},
    {"name": "Deepak Chopra", "title": "Author / Alternative Medicine Advocate", "category": "media", "relationship": "associate", "status": "unknown", "pub": 90, "inst": 70, "nat": "United States", "notes": "[jwiki:deepak-chopra] Globally recognized author and alternative medicine proponent. Maintained a social relationship with Epstein documented in the email archive."},
    {"name": "Peter Mandelson", "title": "British Politician / EU Trade Commissioner", "category": "politics", "relationship": "associate", "status": "unknown", "pub": 80, "inst": 85, "nat": "United Kingdom", "notes": "[jwiki:petermandelson] Senior British Labour politician, former EU Trade Commissioner, and Baron Mandelson. Maintained documented social ties to Epstein raising questions about the nature of their relationship."},
    {"name": "Sultan Bin Sulayem", "title": "Dubai Port Authority Chairman", "category": "finance", "relationship": "associate", "status": "unknown", "pub": 65, "inst": 80, "nat": "United Arab Emirates", "notes": "[jwiki:sultan-bin-sulayem] Chairman of DP World and Dubai Ports Authority, one of the most powerful figures in global shipping and logistics. Email correspondence with Epstein documented in the archive."},
    {"name": "Steve Hanson", "title": "Restaurateur", "category": "entertainment", "relationship": "associate", "status": "unknown", "pub": 45, "inst": 50, "nat": "United States", "notes": "[jwiki:stephen-hanson--3] Prominent New York restaurateur behind B.R. Guest Restaurants. Social relationship with Epstein documented in the email archive."},
    {"name": "Jean-Luc Brunel", "title": "Model Scout / Agency Founder", "category": "entertainment", "relationship": "direct_contact", "status": "deceased", "pub": 60, "inst": 55, "nat": "France", "notes": "[jwiki:jean-luc-brunel] French modeling agent and founder of MC2 Model Management who was accused of procuring underage girls for Epstein. Arrested in Paris in 2020 and found dead in his cell in 2022 while awaiting trial."},
    {"name": "Jes Staley", "title": "Former Barclays CEO", "category": "finance", "relationship": "associate", "status": "unknown", "pub": 75, "inst": 85, "nat": "United States", "notes": "[jwiki:jes-staley-jpmorgan] Former CEO of Barclays and JPMorgan executive who maintained a documented personal friendship with Epstein. Regulators cited his relationship with Epstein in their decision to investigate his conduct."},
    {"name": "Tazia Smith", "title": "Associate", "category": "other", "relationship": "associate", "status": "unknown", "pub": 15, "inst": 15, "nat": "United States", "notes": "[jwiki:tazia-smith] Associate documented in Epstein's email archive with significant correspondence."},
    {"name": "Paul Barrett", "title": "Associate", "category": "other", "relationship": "associate", "status": "unknown", "pub": 20, "inst": 25, "nat": "United States", "notes": "[jwiki:paul-barrett-example] Associate documented in Epstein's email archive."},
    {"name": "Ehud Barak", "title": "Former Israeli Prime Minister", "category": "politics", "relationship": "associate", "status": "unknown", "pub": 90, "inst": 95, "nat": "Israel", "notes": "[jwiki:ehud-barak] Former Prime Minister of Israel, Nobel Peace Prize recipient, and military chief. Maintained a documented friendship with Epstein and was photographed entering his New York townhouse."},
    {"name": "Larry Summers", "title": "Former U.S. Treasury Secretary", "category": "politics", "relationship": "associate", "status": "unknown", "pub": 90, "inst": 95, "nat": "United States", "notes": "[jwiki:larry-summers] Former U.S. Secretary of the Treasury and Harvard University president. Maintained documented contact with Epstein including meetings at Harvard where Epstein provided substantial funding."},
    {"name": "Joscha Bach", "title": "AI Researcher / Cognitive Scientist", "category": "academia", "relationship": "associate", "status": "unknown", "pub": 50, "inst": 55, "nat": "Germany", "notes": "[jwiki:joscha-bach] AI researcher and cognitive scientist with connections to MIT and Harvard. Appears in Epstein's network through academic connections."},
    {"name": "Reid Hoffman", "title": "LinkedIn Co-Founder / Venture Capitalist", "category": "technology", "relationship": "associate", "status": "unknown", "pub": 85, "inst": 90, "nat": "United States", "notes": "[jwiki:reid-hoffman-greylock] Co-founder of LinkedIn and prominent Silicon Valley venture capitalist. Acknowledged meeting Epstein through MIT connections and later expressed regret about those interactions."},
    {"name": "Peter Thiel", "title": "PayPal Co-Founder / Venture Capitalist", "category": "technology", "relationship": "associate", "status": "unknown", "pub": 85, "inst": 90, "nat": "United States", "notes": "[jwiki:peter-thiel] PayPal co-founder, Palantir co-founder, and prominent venture capitalist. Appears in Epstein's network through Silicon Valley and tech industry connections."},
    {"name": "Woody Allen", "title": "Film Director", "category": "entertainment", "relationship": "associate", "status": "unknown", "pub": 90, "inst": 80, "nat": "United States", "notes": "[jwiki:woody-allen] Acclaimed and controversial film director. Appears in Epstein's email archive through social connections in New York elite circles."},
    {"name": "Prince Andrew, Duke of York", "title": "British Royal / Duke of York", "category": "royalty", "relationship": "direct_contact", "status": "unknown", "pub": 95, "inst": 90, "nat": "United Kingdom", "notes": "[jwiki:prince-andrew-duke-of-york] Son of Queen Elizabeth II and former senior working royal. Maintained a well-documented friendship with Epstein and Maxwell. Settled a civil lawsuit brought by Virginia Giuffre in 2022 for an undisclosed sum."},
    {"name": "Leon Black", "title": "Apollo Global Management Founder", "category": "finance", "relationship": "associate", "status": "unknown", "pub": 80, "inst": 90, "nat": "United States", "notes": "[jwiki:leon-black] Billionaire founder of Apollo Global Management, one of the world's largest private equity firms. Paid Epstein over $158 million for financial advice, leading to his resignation as Apollo's CEO."},
    {"name": "Bill Gates", "title": "Microsoft Co-Founder / Philanthropist", "category": "technology", "relationship": "alleged_client", "status": "unknown", "pub": 100, "inst": 100, "nat": "United States", "notes": "[jwiki:bill-gates] Co-founder of Microsoft and one of the world's wealthiest individuals. Met with Epstein multiple times after his 2008 conviction to discuss philanthropic partnerships, meetings Gates later called a mistake."},
    {"name": "Elon Musk", "title": "CEO Tesla & SpaceX", "category": "technology", "relationship": "mentioned_only", "status": "unknown", "pub": 100, "inst": 100, "nat": "United States", "notes": "[jwiki:elon-musk] CEO of Tesla, SpaceX, and owner of X (Twitter). Appears in Epstein's email archive though the nature of any relationship is not clearly established by available documents."},
    {"name": "Alan Dershowitz", "title": "Harvard Law Professor / Defense Attorney", "category": "legal", "relationship": "direct_contact", "status": "unknown", "pub": 85, "inst": 85, "nat": "United States", "notes": "[jwiki:alan-dershowitz] Prominent Harvard Law professor and criminal defense attorney who helped negotiate Epstein's controversial 2008 non-prosecution agreement. Named in civil suits by Virginia Giuffre, which were later settled."},
    {"name": "Casey Wasserman", "title": "Entertainment Executive", "category": "entertainment", "relationship": "mentioned_only", "status": "unknown", "pub": 65, "inst": 70, "nat": "United States", "notes": "[jwiki:casey-wasserman] Prominent entertainment industry executive and grandson of MCA founder Lew Wasserman. Appears in Epstein's files through Hollywood social connections."},
    {"name": "Kimbal Musk", "title": "Entrepreneur / Chef", "category": "technology", "relationship": "mentioned_only", "status": "unknown", "pub": 55, "inst": 55, "nat": "United States", "notes": "[jwiki:kimbal-musk] Entrepreneur, chef, and brother of Elon Musk. Appears in Epstein's email archive through Silicon Valley tech connections."},
    {"name": "Masha Drokova", "title": "Venture Capitalist / Former Putin Youth Leader", "category": "politics", "relationship": "mentioned_only", "status": "unknown", "pub": 45, "inst": 50, "nat": "Russia", "notes": "[jwiki:masha-drokov] Russian venture capitalist who was formerly a leader of the pro-Putin Nashi youth movement. Appears in Epstein's email archive."},
    {"name": "Les Wexner", "title": "L Brands Founder / Billionaire", "category": "finance", "relationship": "direct_contact", "status": "unknown", "pub": 80, "inst": 90, "nat": "United States", "notes": "[jwiki:wexner-les] Founder of L Brands (Victoria's Secret, Bath & Body Works) and Epstein's most important patron. Gave Epstein power of attorney over his finances and gifted him the Manhattan townhouse. Their relationship is considered central to understanding Epstein's wealth."},
    {"name": "Jason Calacanis", "title": "Angel Investor / Podcaster", "category": "technology", "relationship": "mentioned_only", "status": "unknown", "pub": 60, "inst": 60, "nat": "United States", "notes": "[jwiki:jason-calacanis] Silicon Valley angel investor and host of the All-In Podcast. Appears in Epstein's email archive through tech industry connections."},
    {"name": "Bill Clinton", "title": "42nd U.S. President", "category": "politics", "relationship": "associate", "status": "unknown", "pub": 100, "inst": 100, "nat": "United States", "notes": "[jwiki:bill-clinton] 42nd President of the United States. Flew on Epstein's private jet multiple times according to flight logs, and visited Little St. James island. Clinton has denied knowledge of Epstein's crimes."},
    {"name": "Donald Trump", "title": "45th & 47th U.S. President", "category": "politics", "relationship": "mentioned_only", "status": "unknown", "pub": 100, "inst": 100, "nat": "United States", "notes": "[jwiki:donald-trump] 45th and 47th President of the United States. Had a documented social friendship with Epstein in the 1990s and early 2000s in New York and Palm Beach circles before reportedly falling out."},
    {"name": "Justin Trudeau", "title": "Former Canadian Prime Minister", "category": "politics", "relationship": "mentioned_only", "status": "unknown", "pub": 90, "inst": 95, "nat": "Canada", "notes": "[jwiki:justin-trudeau] Former Prime Minister of Canada. Appears in Epstein's files though the nature of any connection is not clearly established by available documents."},
    {"name": "Virginia Giuffre", "title": "Survivor / Plaintiff", "category": "other", "relationship": "victim", "status": "unknown", "pub": 80, "inst": 40, "nat": "United States", "notes": "[jwiki:virginia-giuffre] Primary accuser and survivor who brought civil lawsuits against Epstein, Maxwell, and Prince Andrew. Her testimony and legal actions were instrumental in exposing the full scope of Epstein's trafficking network."},
]


def main():
    print("=== Reckoning Radar - Static Enrichment Pipeline ===")
    print(f"Enriching {len(PROFILES)} profiles (no API calls)")

    supabase = create_client(SUPABASE_URL, SUPABASE_SERVICE_KEY)
    print("✓ Supabase connected")

    success = 0
    errors = 0

    for i, p in enumerate(PROFILES):
        print(f"[{i+1}/{len(PROFILES)}] {p['name']}")

        update = {
            "public_title": p["title"],
            "category": p["category"],
            "relationship_to_epstein": p["relationship"],
            "current_status": p["status"],
            "notes": p["notes"],
            "power_public_profile": p["pub"],
            "power_institutional": p["inst"],
            "confidence": "indicated",
        }
        if p.get("nat"):
            update["nationality"] = [p["nat"]]

        try:
            supabase.table("persons").update(update).eq("full_name", p["name"]).execute()
            success += 1
            print(f"  ✓ {p['category']} | {p['relationship']}")
        except Exception as e:
            print(f"  ✗ Error: {e}")
            errors += 1

        time.sleep(0.1)

    print(f"\n=== DONE: {success} enriched, {errors} failed ===")


if __name__ == "__main__":
    main()
